#ifndef _TOOL_PICK_OBJECT_SDK_H_
#define _TOOL_PICK_OBJECT_SDK_H_

enum
{
	MDATA_PICKOBJECT_MODE					= 2000,
		MDATA_PICKOBJECT_MODE_CIRCLE = 0,
		MDATA_PICKOBJECT_MODE_RECTANGLE = 1,
	MDATA_PICKOBJECT_ONLY_VISIBLE = 2001,
	MDATA_PICKOBJECT_CIRCLE_RAD		= 2002,
	MDATA_PICKOBJECT_RECT_W				= 2003,
	MDATA_PICKOBJECT_RECT_H				= 2004
};

#endif // _TOOL_PICK_OBJECT_SDK_H_
