#ifndef _Xbitmapdistortion_H_
#define _Xbitmapdistortion_H_

enum
{
	BITMAPDISTORTIONSHADER_NOISE 		= 1000,
	BITMAPDISTORTIONSHADER_OCTAVES	= 1001,
	BITMAPDISTORTIONSHADER_SCALE		= 1002,
	BITMAPDISTORTIONSHADER_TEXTURE	= 1003
};

#endif