#ifndef _Xmandelbrot_H_
#define _Xmandelbrot_H_

enum
{
	MANDELBROTSHADER_COLOROFFSET	= 1000,
	MANDELBROTSHADER_OBJECTACCESS	= 1001,
	MANDELBROTSHADER_THREADRATIO	= 1002,
	WEAVESHADER_WARPPATTERN			= 1003,
	WEAVESHADER_WARPOFFSET			= 1004
};

#endif