CONTAINER Xpalette
{
	NAME Xpalette;

	INCLUDE Mpreview;
	INCLUDE Xbase;

	GROUP ID_SHADERPROPERTIES
	{
		LONG PALETTESHADER_PALETTE_ID {MIN 0; MAX 99;}
		LONG PALETTESHADER_COLOR_ID   {MIN 0; MAX 99;}
	}
}
