#pragma once

#pragma message("TODO: get unique plugin ids")
#define COLORPICKER_ID    1018404
#define COLORSELECTOR_ID 1018407
#define PALETTE_ID 1018408
#define PALETTE2_ID 1018409
#define PALETTE3_ID 1018410
#define PALETTE_SCENE_HOOK_ID 1018411
#define COLORPICKER_ENABLE_ID 1018412
#define PALETTE_SHADER_ID 1018413


//////////////////////////////////////////////////////////////////////////

enum
{
	IDC_COLORWHEEL	= 1001,
	IDC_COLORBOX,
	IDC_R,
	IDC_G,
	IDC_B,
	IDC_C,
	IDC_M,
	IDC_Y,
	IDC_K,
    IDC_H,
    IDC_S,
    IDC_V,
    IDC_L,
    IDC_A,
    IDC_BB,
    IDC_ROWS,
    IDC_LAYOUT_DIRECTION,
	IDC_RSLIDER,
	IDC_GSLIDER,
	IDC_BSLIDER,
	IDC_CSLIDER,
	IDC_MSLIDER,
	IDC_YSLIDER,
	IDC_KSLIDER,
    IDC_HSLIDER,
    IDC_SSLIDER,
    IDC_VSLIDER,
    IDC_LSLIDER,
    IDC_ASLIDER,
    IDC_BBSLIDER,
	IDC_RGBICC,
	IDC_CMYKICC,
    IDC_HSVICC,
	IDC_HEXTEXT,
	IDC_PALETTE,
	IDC_SLIDERS,
	IDC_SCHEMECOMBO,
	IDC_LABELCHECKBOX,
	IDC_SEARCHTEXT,
    IDC_NAME,
    IDC_CREATEMATERIAL,
    IDC_FILTERLABEL,
    IDC_HIDE,
	IDC_ICCLABEL,
	IDC_TEST1,
	IDC_TEST2,
	IDC_TEST3,
	IDC_TEST4,
	IDC_TEST5,
	IDC_TEST6,
	IDC_TEST7,
	IDC_TEST8,
	IDC_TEST9,
	IDC_TEST10,
	IDC_TEST11,
	IDC_LASTENTRY,
};