#pragma once

#pragma message("TODO: get unique plugin ids")
#define COLORPICKER_ID    1018404
#define SPOTCOLOR_ID    1018405
#define COLORSELECTOR_ID 1018407
#define PALETTE_ID 1018408
#define PALETTE_SCENE_HOOK_ID 1018409


//////////////////////////////////////////////////////////////////////////

enum
{
	IDC_COLORWHEEL	= 1001,
	IDC_COLORBOX,
	IDC_R,
	IDC_G,
	IDC_B,
	IDC_C,
	IDC_M,
	IDC_Y,
	IDC_K,
	IDC_RSLIDER,
	IDC_GSLIDER,
	IDC_BSLIDER,
	IDC_CSLIDER,
	IDC_MSLIDER,
	IDC_YSLIDER,
	IDC_KSLIDER,
	IDC_RGBICC,
	IDC_CMYKICC,
	IDC_SPOTICC,
	IDC_HEXTEXT,
	IDC_PALETTE,
	IDC_SLIDERS,
	IDC_SCHEMECOMBO,
	IDC_LABELCHECKBOX,
	IDC_SEARCHTEXT,
	IDC_ICCLABEL,
	IDC_TEST1,
	IDC_TEST2,
	IDC_TEST3,
	IDC_TEST4,
	IDC_TEST5,
	IDC_TEST6,
	IDC_TEST7,
	IDC_TEST8,
	IDC_TEST9,
	IDC_TEST10,
	IDC_TEST11,
	IDC_LASTENTRY,
};